### ISSUE TITLE
'str' object has no attribute 'getImgIds'

### ISSUE THREAD

**Issue by water500ml** [njucckevin/KnowCap#3]
Traceback (most recent call last):
  File "train_multitask.py", line 228, in <module>
    pycoco_results = eval_pycoco(config, gen_pycoco_path, 'val')
  File "/home/tuxiangsuo1502/KnowCap/utils/eval.py", line 80, in eval_pycoco
    cocoEval = COCOEvalCap('diy', 'diy')
  File "/home/tuxiangsuo1502/miniconda3/envs/hjl/lib/python3.7/site-packages/pycocoevalcap/eval.py", line 17, in __init__
    self.params = {'image_id': coco.getImgIds()}
AttributeError: 'str' object has no attribute 'getImgIds
 Do you have any clue when I encountered the above problems while starting training from scratch Thank you in advance for your reply

**Comment by njucckevin** [comment]
Hi, sorry that I missed the custom evaluation function. Now I added an `eval.py`, which I used to replace the one in `xxx/site-packages/pycocoevalcap/eval.py` for our evaluation. We also update the evaluation section in readme for this.
Thanks for the heads up.

**Comment by reemaljunaid94** [comment]
running this code will solve the error? "!cp /content/drive/My\ Drive/KnowCap-master/eval.py /usr/local/lib/python3.11/dist-packages/pycocoevalcap/eval.py
"

**Comment by reemaljunaid94** [comment]
At the beginning I saw the losses and every thing fine however I faced this error AttributeError: 'str' object has no attribute 'getImgIds. 
Then I tried to run this '!cp /content/drive/My\ Drive/KnowCap-master/eval.py /usr/local/lib/python3.11/dist-packages/pycocoevalcap/eval.py' but I encountered 'OSError: [Errno 5] Input/output error: '/content/drive/My Drive/Datasets/COCO2014/val2014/COCO_val2014_000000411368.jpg' even though the image is exist and i have set the number or worker to zero.  



'
